<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="DESKTOP-2GB3AA6" failures="1" tests="2" name="Default test(failed)" time="0.135" errors="0" timestamp="2024-05-18T13:52:46 IST">
  <testcase classname="com.learn.retryfailedtest.RetryFailedTestDemo" name="test2" time="0.016">
    <failure type="java.lang.ArithmeticException" message="/ by zero">
      <![CDATA[java.lang.ArithmeticException: / by zero
at com.learn.retryfailedtest.RetryFailedTestDemo.test2(RetryFailedTestDemo.java:16)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
  <testcase classname="com.learn.retryfailedtest.RetryFailedTestDemo" name="test3" time="0.004"/>
  <testcase classname="com.learn.retryfailedtest.RetryFailedTestDemo" name="test1" time="0.0">
    <ignored/>
  </testcase> <!-- test1 -->
</testsuite> <!-- Default test(failed) -->
